name: Trivy Security Scan

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  trivy-scan:
    uses: Steinpilz/it-autodevops/.github/workflows/sup-trivy-scan.yml@sup-4.7
    with:
      exit-code: "1"
    permissions:
      actions: read
      contents: read
      security-events: write
